version: '3.0'

services:
  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    command:
      - --workers=http://worker_1:2375,http://worker_2:2375
    links:
      - worker
    ports:
      - 2375:2375
  worker:
    image: docker:17.11.0-ce-dind
    privileged: true
    environment:
      DOCKER_DRIVER: overlay2
