apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
  replicas: 1
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: registry
          image: registry:2.6.2
          ports:
            - containerPort: 5000
              name: registry
          livenessProbe:
            tcpSocket:
              port: 5000
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: cache
spec:
  clusterIP: None
  ports:
    - port: 5000
  selector:
    app: cache
