apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtools
spec:
  selector:
    matchLabels:
      app: devtools
  replicas: 1
  template:
    metadata:
      labels:
        app: devtools
    spec:
      containers:
        - name: devtools
          image: devtools-image
          imagePullPolicy: Never
          args:
            - sh
            - -c
            - "sleep infinity"
          env:
            - name: DOCKER_HOST
              value: tcp://docker:2375
