apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  selector:
    matchLabels:
      app: dispatcher
  replicas: 1
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
        - name: dispatcher
          image: dispatcher-image
          imagePullPolicy: Never
          args:
            - --workers=http://builder-0.builder:2375,http://builder-1.builder:2375,http://builder-2.builder:2375,http://builder-3.builder:2375
          ports:
            - containerPort: 2375
              name: docker
          livenessProbe:
            tcpSocket:
              port: 2375
          readinessProbe:
            httpGet:
              path: /healthz
              port: 2375
---
kind: Service
apiVersion: v1
metadata:
  name: docker
spec:
  clusterIP: None
  ports:
    - port: 2375
  selector:
    app: dispatcher
